name: run-buildifier
on: [push]
jobs:
  run-buildifier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v1.0.1
      - name: Mount bazel cache
        uses: actions/cache@v1
        with:
          path: "~/.cache/bazel"
          key: bazel
      - name: Run Buildifier
        run: bazel run //:buildifier -- --lint=warn --warnings=all -r .
